INSERT INTO "public"."categories" ("name", "title", "description", "image_url") VALUES ( 'household-goods', 'Reusable Household Goods for Everyday Use', 'Make a positive impact with our durable, reusable items.', '/category-images/household-goods.jpg'),
 ( 'skincare', 'Organic Skincare for a Natural Glow', 'Nourish your skin with our eco-friendly skincare line.', '/category-images/skincare.jpg'),
 ( 'clothing', 'Eco-Friendly Clothing for Sustainable Fashion', 'Dress sustainably with our stylish, ethical apparel.', '/category-images/clothing.jpg');

INSERT INTO "public"."products" ("name", "description", "price", "quantity", "image_url", "category_id", "title") VALUES
  ('glass-and-bamboo-food-container', 'These glass and bamboo food containers are made with zero plastic, BPAs, or other harmful materials, and are designed to be reused endlessly. High borosilicate glass is ultra-durable, temperature-resistant, easy to clean, and makes viewing your leftovers or pantry staples a breeze.', '22.00', '5', '/product-images/glass-and-bamboo-food-container.webp', '1', 'Glass and Bamboo Food Container'),
  ('sustainable-bottle-cleaning-brush', 'Keep your reusable water bottle clean with this low-impact bottle brush made from sustainable beech wood and coconut fibers.', '12.00', '10', '/product-images/sustainable-bottle-cleaning-brush.webp', '1', 'Sustainable Bottle Cleaning Brush'), 
  ('produce-bag-bundle-cotton', 'These bags hold everything! Perfect for produce, bulk dry ingredients, and other groceries. These easy-to-use, lightweight bags eliminate the need for disposable plastic bags.', '12.00', '15', '/product-images/produce-bag-bundle-cotton.webp', '1', 'Produce Bag Bundle - Cotton'), 
  ('airtight-stainless-steel-containers', 'Store meal prep, leftovers, lunches, and more in sleek, sustainable, stainless steel. Made of high-quality food-grade stainless steel and equipped with silicone lid seals and latches for zero spills.', '20.00', '0', '/product-images/airtight-stainless-steel-containers.webp', '1', 'Airtight Stainless Steel Containers'),
  ('reusable-bamboo-cutlery-set', 'Practical, lightweight, and 100% natural, bamboo is durable, heat-resistant, stain-resistant, and doesn’t absorb flavors – making this limited-edition utensil set is the perfect zero-waste swap for meals on the go.', '12.95', '3', '/product-images/reusable-bamboo-cutlery-set.webp', '1', 'Reusable Bamboo Cutlery Set'), 
  ('conditioner-bar', 'This 100% biodegradable and naturally-derived conditioner bar lasts 2-3x longer than liquid products and is free of parabens, sulfates, and artificial fragrances.', '19.00', '5', '/product-images/conditioner-bar.webp', '2', 'Conditioner Bar'),
  ('shampoo-bar', 'This 100% biodegradable and naturally-derived shampoo bar lasts 2-3x longer than liquid products and is free of parabens, sulfates, and artificial fragrances.', '19.00', '5', '/product-images/shampoo-bar.webp', '2', 'Shampoo Bar'), 
  ('body-bar', 'This 100% biodegradable and naturally-derived body bar lasts 2-3x longer than liquid washes and is free of parabens, sulfates, and artificial fragrances.', '19.00', '5', '/product-images/body-bar.webp', '2', 'Body Bar'),
  ('natural-refillable-body-wash', 'Blended with the finest organic, vegan ingredients it gently cleans while restoring nutrients and powerful antioxidants to your skin. Daily use improves skin’s tone and texture.', '30.00', '0', '/product-images/natural-refillable-body-wash.webp', '2', 'Natural Refillable Body Wash'),
  ('matcha-under-eye-balm', 'This collagen boosting, regenerative Matcha Vegan Under Eye & Lip Balm from Buju Skin is here to smooth and smooth. And it’s not just for your eyes! Handmade with ultra moisturizing Organic coconut oil, shea butter, and candelilla wax, you can slather this Balm on your skin, under eye area, and mouth.', '17.00', '10', '/product-images/matcha-under-eye-balm.webp', '2', 'Matcha Under Eye Balm'),
  ('mens-classic-retro-x-windproof-fleece-jacket', 'Windproof and warm for cool, blustery weather, our Classic Retro-X® Jacket is a favorite fleece built with a 100% polyester (85% recycled) ¼"-pile face that''s bonded to a mesh backer.', '229.00', '20', '/product-images/mens-classic-retro-x-windproof-fleece-jacket.jpg', '3', 'Men''s Classic Retro-X Windproof Fleece Jacket'),
  ('mens-better-sweater-fleece-jacket', 'This warm, 100% recycled polyester full-zip jacket combines a sweater-knit aesthetic with the easy care of Better Sweater fleece. It’s dyed with a low-impact process that reduces the use of dyestuffs, energy and water compared to conventional heather dyeing methods.', '159.00', '10', '/product-images/mens-better-sweater-fleece-jacket.jpg', '3', 'Men''s Better Sweater Fleece Jacket'),
  ('mens-long-sleeved-capilene-cool-daily-shirt', 'Our most versatile technical top is designed for use on the trail or on the water: It’s quick drying, has stretch for mobility and comfort, and HeiQ® Mint odor control for long-lasting freshness. Built with 50-100% recycled polyester, Capilene® Cool Daily styles keep you comfortable when you’re working hard in conditions ranging from cool to hot.', '55.00', '0', '/product-images/mens-long-sleeved-capilene-cool-daily-shirt.jpg', '3', 'Men''s Long-Sleeved Capilene Cool Daily Shirt'),
  ('mens-daily-sweatpants', 'Embrace the basics in our cozy, long-lasting Daily Sweatpants. Whether you’re relaxing at home or getting after it outdoors, these versatile, go-to sweatpants keep you warm, comfortable and free to move.', '119.00', '2', '/product-images/mens-daily-sweatpants.jpg', '3', 'Men''s Daily Sweatpants'),
  ('mens-twill-traveler-5-pocket-pants-regular', 'Classic, go-to pants designed for daily wear, utility and moving in comfort, the Twill Traveler 5-Pocket Pants are made with a durable, moisture-wicking blend of organic cotton and polyester twill.', '129.00', '15', '/product-images/mens-twill-traveler-5-pocket-pants-regular.jpg', '3', 'Men''s Twill Traveler 5-Pocket Pants Regular');